-- 001_schema.sql — the consolidated schema (squash of the original 001–018).
--
-- Every entity is an ID-ONLY anchor; all of its attributes live in edit-grouped
-- temporal FACT tables keyed by `(anchor_id, <period> WITHOUT OVERLAPS)` (ADR-030).
-- Two read modes: valid-time AS-OF over the semantic `*_during` periods, and
-- latest-read over `recorded_during`/`planned_during` (transaction-time) via the
-- `*_current` views. Containment is enforced by PERIOD foreign keys (`*_within_*`);
-- non-overlap by `WITHOUT OVERLAPS` primary keys (`*_no_overlap`); value ranges by
-- `CHECK` (`*_check`). Those constraint-name suffixes are load-bearing: the app
-- classifies a rejection into a typed OperationError by the violated name (ADR-022).
--
-- Anchor ids are app-driven: each command-minted anchor owns an id sequence
-- (`<anchor>_id_seq`, the implicit sequence of a BY DEFAULT identity), so a handler
-- reserves the next id with `nextval` and threads it into every fact it records
-- (no RETURNING read-back). `event_log` mints its own id (GENERATED ALWAYS).

CREATE EXTENSION IF NOT EXISTS btree_gist;  -- GiST support for daterange WITHOUT OVERLAPS / EXCLUDE

-- Identity anchors ------------------------------------------------------------
-- ID-ONLY: no attributes here; those hang off in the fact tables below. BY DEFAULT
-- identity so the seed can pin explicit ids and the app can supply ids it reserved
-- from the same sequence via nextval.
CREATE TABLE engineer     (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE client       (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE contract     (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE project      (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE invoice      (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE payroll_run  (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);

-- Provenance journal ----------------------------------------------------------
-- One row per applied command: who did what, when (SYSTEM time). `occurred_at` is
-- the real wall clock (the seed back-dates it to a realistic timeline); valid-time
-- "now" is the fixed seed date. `id` doubles as the order applied.
CREATE TABLE event_log (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  actor       text  NOT NULL,
  operation   text  NOT NULL,
  summary     text  NOT NULL,
  payload     jsonb NOT NULL
);

-- Workforce: employment is the root of the PERIOD-FK containment chain ---------
CREATE TABLE employment (
  engineer_id     int NOT NULL REFERENCES engineer(id),
  employed_during daterange NOT NULL,
  CONSTRAINT employment_no_overlap PRIMARY KEY (engineer_id, employed_during WITHOUT OVERLAPS)
);

CREATE TABLE engineer_role (
  engineer_id int NOT NULL,
  level       int NOT NULL CONSTRAINT engineer_role_level_check CHECK (level BETWEEN 1 AND 7),
  held_during daterange NOT NULL,
  CONSTRAINT engineer_role_no_overlap PRIMARY KEY (engineer_id, held_during WITHOUT OVERLAPS),
  CONSTRAINT engineer_role_within_employment
    FOREIGN KEY (engineer_id, PERIOD held_during)
    REFERENCES employment (engineer_id, PERIOD employed_during)
);

-- engineer_contact carries the NAME (the anchor is id-only); contact/banking/
-- emergency are latest-read facts (recorded_during = transaction time).
CREATE TABLE engineer_contact (
  engineer_id    int NOT NULL REFERENCES engineer(id),
  name           text NOT NULL,
  email          text NOT NULL,
  phone          text NOT NULL,
  postal_address text NOT NULL,
  recorded_during daterange NOT NULL,
  CONSTRAINT engineer_contact_no_overlap PRIMARY KEY (engineer_id, recorded_during WITHOUT OVERLAPS)
);

CREATE TABLE engineer_banking (
  engineer_id  int NOT NULL REFERENCES engineer(id),
  bank         text NOT NULL,
  branch       text NOT NULL,
  account_no   text NOT NULL,
  account_name text NOT NULL,
  recorded_during daterange NOT NULL,
  CONSTRAINT engineer_banking_no_overlap PRIMARY KEY (engineer_id, recorded_during WITHOUT OVERLAPS)
);

CREATE TABLE engineer_emergency (
  engineer_id int NOT NULL REFERENCES engineer(id),
  relation    text NOT NULL,
  name        text NOT NULL,
  phone       text NOT NULL,
  email       text NOT NULL,
  recorded_during daterange NOT NULL,
  CONSTRAINT engineer_emergency_no_overlap PRIMARY KEY (engineer_id, recorded_during WITHOUT OVERLAPS)
);

CREATE TABLE leave (
  engineer_id int NOT NULL,
  kind        text NOT NULL,
  on_leave_during daterange NOT NULL,
  CONSTRAINT leave_no_overlap PRIMARY KEY (engineer_id, on_leave_during WITHOUT OVERLAPS),
  CONSTRAINT leave_within_employment
    FOREIGN KEY (engineer_id, PERIOD on_leave_during)
    REFERENCES employment (engineer_id, PERIOD employed_during)
);

-- Engagement: contract → its terms; project → its run/profile/plan -------------
CREATE TABLE contract_terms (
  contract_id int NOT NULL REFERENCES contract(id),
  client_id   int NOT NULL REFERENCES client(id),
  term        daterange NOT NULL,
  CONSTRAINT contract_terms_no_overlap PRIMARY KEY (contract_id, term WITHOUT OVERLAPS)
);

CREATE TABLE project_run (
  project_id    int NOT NULL REFERENCES project(id),
  contract_id   int NOT NULL,
  active_during daterange NOT NULL,
  CONSTRAINT project_run_no_overlap PRIMARY KEY (project_id, active_during WITHOUT OVERLAPS),
  CONSTRAINT project_within_contract
    FOREIGN KEY (contract_id, PERIOD active_during)
    REFERENCES contract_terms (contract_id, PERIOD term)
);

CREATE TABLE project_profile (
  project_id int NOT NULL REFERENCES project(id),
  title      text NOT NULL,
  summary    text NOT NULL,
  recorded_during daterange NOT NULL,
  CONSTRAINT project_profile_no_overlap PRIMARY KEY (project_id, recorded_during WITHOUT OVERLAPS)
);

CREATE TABLE project_plan (
  project_id        int NOT NULL REFERENCES project(id),
  budget            numeric(12,2) NOT NULL CONSTRAINT project_plan_budget_check CHECK (budget >= 0),
  target_completion date NOT NULL,
  planned_during    daterange NOT NULL,
  CONSTRAINT project_plan_no_overlap PRIMARY KEY (project_id, planned_during WITHOUT OVERLAPS)
);

CREATE TABLE allocation (
  engineer_id int NOT NULL,
  project_id  int NOT NULL,
  fraction    numeric(3,2) NOT NULL CONSTRAINT allocation_fraction_check CHECK (fraction > 0 AND fraction <= 1),
  allocated_during daterange NOT NULL,
  CONSTRAINT allocation_no_overlap PRIMARY KEY (engineer_id, project_id, allocated_during WITHOUT OVERLAPS),
  CONSTRAINT allocation_project_fkey FOREIGN KEY (project_id) REFERENCES project(id),
  CONSTRAINT allocation_within_employment
    FOREIGN KEY (engineer_id, PERIOD allocated_during)
    REFERENCES employment (engineer_id, PERIOD employed_during),
  CONSTRAINT allocation_within_project
    FOREIGN KEY (project_id, PERIOD allocated_during)
    REFERENCES project_run (project_id, PERIOD active_during)
);

CREATE TABLE timesheet (
  engineer_id int NOT NULL,
  project_id  int NOT NULL,
  work_day    daterange NOT NULL,
  hours       numeric(4,2) NOT NULL CONSTRAINT timesheet_hours_check CHECK (hours > 0 AND hours <= 24),
  CONSTRAINT timesheet_no_overlap PRIMARY KEY (engineer_id, project_id, work_day WITHOUT OVERLAPS),
  CONSTRAINT timesheet_within_allocation
    FOREIGN KEY (engineer_id, project_id, PERIOD work_day)
    REFERENCES allocation (engineer_id, project_id, PERIOD allocated_during)
);

-- Client profile (latest-read fact off the client anchor) ---------------------
CREATE TABLE client_profile (
  client_id int NOT NULL REFERENCES client(id),
  name      text NOT NULL,
  recorded_during daterange NOT NULL,
  CONSTRAINT client_profile_no_overlap PRIMARY KEY (client_id, recorded_during WITHOUT OVERLAPS)
);

-- Pricing & cost: what we CHARGE (rate_card) and what we PAY (salary) ----------
CREATE TABLE rate_card (
  level     int NOT NULL CONSTRAINT rate_card_level_check CHECK (level BETWEEN 1 AND 7),
  day_rate  numeric(10,2) NOT NULL,
  effective_during daterange NOT NULL,
  CONSTRAINT rate_card_no_overlap PRIMARY KEY (level, effective_during WITHOUT OVERLAPS)
);

CREATE TABLE salary (
  level          int NOT NULL CONSTRAINT salary_level_check CHECK (level BETWEEN 1 AND 7),
  monthly_salary numeric(10,2) NOT NULL,
  effective_during daterange NOT NULL,
  CONSTRAINT salary_no_overlap PRIMARY KEY (level, effective_during WITHOUT OVERLAPS)
);

-- Invoice: anchor + immutable subject, temporal status, snapshot lines ---------
CREATE TABLE invoice_subject (
  invoice_id     int NOT NULL REFERENCES invoice(id) PRIMARY KEY,
  project_id     int NOT NULL REFERENCES project(id),
  billing_period daterange NOT NULL,
  CONSTRAINT invoice_subject_within_project
    FOREIGN KEY (project_id, PERIOD billing_period)
    REFERENCES project_run (project_id, PERIOD active_during)
);

CREATE TABLE invoice_status (
  invoice_id int NOT NULL REFERENCES invoice(id),
  status     text NOT NULL CONSTRAINT invoice_status_status_check CHECK (status IN ('draft', 'issued', 'paid')),
  status_during daterange NOT NULL,
  CONSTRAINT invoice_status_no_overlap PRIMARY KEY (invoice_id, status_during WITHOUT OVERLAPS)
);

CREATE TABLE invoice_line (
  invoice_id  int NOT NULL REFERENCES invoice(id),
  engineer_id int NOT NULL CONSTRAINT invoice_line_engineer_fkey REFERENCES engineer(id),
  level       int NOT NULL,
  day_rate    numeric(10,2) NOT NULL,
  days        numeric(8,2) NOT NULL,
  amount      numeric(12,2) NOT NULL
);

-- Payroll: anchor + immutable period (one run per month) + lines ---------------
CREATE TABLE payroll_period (
  run_id int NOT NULL REFERENCES payroll_run(id) PRIMARY KEY,
  period daterange NOT NULL,
  CONSTRAINT payroll_period_no_overlap EXCLUDE USING gist (period WITH &&)
);

CREATE TABLE payroll_line (
  run_id      int NOT NULL REFERENCES payroll_run(id),
  engineer_id int NOT NULL CONSTRAINT payroll_line_engineer_fkey REFERENCES engineer(id),
  amount      numeric(12,2) NOT NULL,
  days        numeric(8,2) NOT NULL
);

-- Latest-read views: the most-recently-recorded version per anchor -------------
CREATE VIEW client_current AS
  SELECT DISTINCT ON (client_id) client_id AS id, name
    FROM client_profile ORDER BY client_id, lower(recorded_during) DESC;

CREATE VIEW engineer_current AS
  SELECT DISTINCT ON (engineer_id) engineer_id AS id, name, email, phone, postal_address
    FROM engineer_contact ORDER BY engineer_id, lower(recorded_during) DESC;

CREATE VIEW project_current AS
  SELECT DISTINCT ON (project_id) project_id AS id, title, summary
    FROM project_profile ORDER BY project_id, lower(recorded_during) DESC;

-- Per-fact provenance ---------------------------------------------------------
-- A fact links to the event_log entry (the command) that recorded THAT row-version,
-- so a row can be traced back to who wrote it and when. The repository sets audit_id
-- explicitly on each write (and the seed sets it inline): an insert supplies it as a
-- column; a FOR PORTION OF Change SETs it on the changed [from, NULL) portion while
-- PG copies the row onto the carved-off leftover (keeping its ORIGINAL audit_id); a
-- delete (a retraction's cap) leaves no row, so a retraction's provenance lives only
-- in event_log. This is a provenance pointer, NOT a temporal axis — the as-of reads
-- never consult audit_id, so the model stays valid-time-only (ADR-021, as amended by
-- ADR-032). Nullable so low-level constraint-test fixtures that insert facts directly
-- (bypassing the repository) need not fabricate an entry.
ALTER TABLE employment        ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE engineer_role     ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE engineer_contact  ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE engineer_banking  ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE engineer_emergency ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE leave             ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE contract_terms    ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE project_run       ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE project_profile   ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE project_plan      ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE allocation        ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE timesheet         ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE client_profile    ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE rate_card         ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE salary            ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE invoice_subject   ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE invoice_status    ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE invoice_line      ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE payroll_period    ADD COLUMN audit_id bigint REFERENCES event_log(id);
ALTER TABLE payroll_line      ADD COLUMN audit_id bigint REFERENCES event_log(id);
