-- 20260704090000_capabilities_skills.sql — capability & skill taxonomy (#38).
--
-- Two anchors (capability, skill), each with a temporal profile fact for its
-- name/summary. capability_skill is a weighted M2M mapping a capability to the
-- skills that compose it (weight 1-3, how much that skill counts toward the
-- capability's rollup). engineer_skill is a per-engineer, per-skill assessed
-- level (0-4), contained within the engineer's employment via a PERIOD FK — the
-- same containment chain as engineer_role.
--
-- All four temporal tables declare their WITHOUT OVERLAPS primary key DEFERRABLE
-- INITIALLY IMMEDIATE so the delete-then-insert upsert (DELETE FOR PORTION OF +
-- INSERT in one CTE) is checked once after both apply, not mid-statement — the
-- same treatment as client_profile/engineer_role/workflow_step_value.
--
-- capability_profile/skill_profile/capability_skill carry no PERIOD FK — the
-- taxonomy is not contained within any other temporal fact, just plain FKs to
-- the anchors. engineer_skill IS contained within employment, like engineer_role.

CREATE TABLE capability (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
CREATE TABLE skill      (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);

CREATE TABLE capability_profile (
  capability_id  int NOT NULL REFERENCES capability(id),
  name           text NOT NULL,
  summary        text NOT NULL,
  defined_during daterange NOT NULL,
  audit_id       bigint REFERENCES event_log(id),
  CONSTRAINT capability_profile_no_overlap
    PRIMARY KEY (capability_id, defined_during WITHOUT OVERLAPS)
    DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE skill_profile (
  skill_id       int NOT NULL REFERENCES skill(id),
  name           text NOT NULL,
  summary        text NOT NULL,
  defined_during daterange NOT NULL,
  audit_id       bigint REFERENCES event_log(id),
  CONSTRAINT skill_profile_no_overlap
    PRIMARY KEY (skill_id, defined_during WITHOUT OVERLAPS)
    DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE capability_skill (
  capability_id int NOT NULL REFERENCES capability(id),
  skill_id      int NOT NULL REFERENCES skill(id),
  weight        int NOT NULL CONSTRAINT capability_skill_weight_check CHECK (weight BETWEEN 1 AND 3),
  mapped_during daterange NOT NULL,
  audit_id      bigint REFERENCES event_log(id),
  CONSTRAINT capability_skill_no_overlap
    PRIMARY KEY (capability_id, skill_id, mapped_during WITHOUT OVERLAPS)
    DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE engineer_skill (
  engineer_id     int NOT NULL,
  skill_id        int NOT NULL REFERENCES skill(id),
  level           int NOT NULL CONSTRAINT engineer_skill_level_check CHECK (level BETWEEN 0 AND 4),
  assessed_during daterange NOT NULL,
  audit_id        bigint REFERENCES event_log(id),
  CONSTRAINT engineer_skill_no_overlap
    PRIMARY KEY (engineer_id, skill_id, assessed_during WITHOUT OVERLAPS)
    DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT engineer_skill_within_employment
    FOREIGN KEY (engineer_id, PERIOD assessed_during)
    REFERENCES employment (engineer_id, PERIOD employed_during)
);

CREATE INDEX capability_profile_audit_id_idx ON capability_profile (audit_id);
CREATE INDEX skill_profile_audit_id_idx      ON skill_profile (audit_id);
CREATE INDEX capability_skill_audit_id_idx   ON capability_skill (audit_id);
CREATE INDEX engineer_skill_audit_id_idx     ON engineer_skill (audit_id);

CREATE VIEW capability_current AS
  SELECT capability_id AS id, name, summary
    FROM capability_profile WHERE upper_inf(defined_during);

CREATE VIEW skill_current AS
  SELECT skill_id AS id, name, summary
    FROM skill_profile WHERE upper_inf(defined_during);
