-- 20260626120000_account_credentials.sql — login credentials for real password auth.
--
-- Auth credentials are infrastructure, not an edit-grouped temporal FACT: there is
-- no valid-time history to query, so this is a plain table rather than the
-- anchor + `*_during` pattern the domain entities use. One row per login identity:
--   * username      — the login id (an email); UNIQUE so it addresses one account
--   * display_name  — the actor stamped on the journal ("Priya Sharma", "Admin"),
--                     unchanged from the demo gate so authorization + audit are intact
--   * role          — drives auth.authorize; mirrors the auth.Role variants
--   * password_hash — a self-describing PBKDF2-HMAC-SHA512 hash string
--                     (account/password.gleam); never a plaintext password
--
-- The rows are DEV-only and seeded by `tempo/seed` (argus-hashed), never by a
-- migration — a deploy applies this table empty and provisions real accounts itself.
CREATE TABLE account (
  id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL UNIQUE,
  display_name  text NOT NULL,
  role          text NOT NULL CHECK (role IN ('admin', 'ops', 'engineer')),
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
